### ISSUE TITLE
Playback status issue

### ISSUE THREAD

**Issue by narakai** [rohansohonee/ufmp#1]
**Describe the bug**
Playback status and duration not correct when skipping to a previous song.

**To Reproduce**
1. Play a song and go to Now Playing page.
2. Click previous icon to skip to a previous song.
3. When the song starts to play, click pause icon.

**Expected behavior**
The song should be in paused state, but it still continues to play, and the duration will be different when switching between play state and pause state.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPod
 - OS: iOS 12.4.5

**Additional context**
I also tried on my Android phone and it seems fine on Android.

Found some logs which shows pause action is failed on iOS:

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: Can call pause only from playing and buffering states (AudioPlaybackState.stopped)
#0      AudioPlayer.pause (package:just_audio/just_audio.dart:329:9)
#1      AudioPlayerTask.onPause (package:ufmp/service/audioPlayerTask.dart:89:18)
#2      AudioServiceBackground.run.<anonymous closure> (package:audio_service/audio_service.dart:847:16)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
#6      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:54:29)
#7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _invoke3 (dart:ui/hooks.dart:302:10)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)

**Comment by rohansohonee** [comment]
Hi @narakai 
>[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: Can call pause only from playing and buffering states (AudioPlaybackState.stopped)

the current state of the audioplayer is in ``AudioPlaybackState.stopped``.
>AudioPlayerTask.onPause (package:ufmp/service/audioPlayerTask.dart:89:18)

Line [89](https://github.com/rohansohonee/ufmp/blob/master/lib/service/audioPlayerTask.dart#L89) will require to check current playback is in ``playing`` and ``bufferring`` states.

I do not own an iOS device currently. You can try the fix I have mentioned and test for iOS.
**PR's are welcome**

**Comment by narakai** [comment]
Hi, I have added current playback check and play/pause is fine now, but the duration starts to count immediately after skipping to the new song (seems it is in buffing state, not in started status yet).

**Comment by rohansohonee** [comment]
@narakai 
Can you open a new issue for the duration bug, this will help keep things organized. Also open a PR with the playback check you have added. I will close this issue when the PR has been merged.
