### ISSUE TITLE
[Unrelated] Please provide information on how to fetch data from firebase and use that

### ISSUE THREAD

**Issue by Chandra-shekar-shetty** [rohansohonee/ufmp#4]
**Describe your suggestion**

**Comment by rohansohonee** [comment]
@Chandra-shekar-shetty 

You can first go through the docs of `audio_service` plugin https://github.com/ryanheise/audio_service/wiki/Tutorial. I have also mentioned this in the README. After going through the above link please describe in detail what part of the sample you want documented. Also please follow the documentation template by filling in the necessary fields.

**Comment by Chandra-shekar-shetty** [comment]
@rohansohonee 
I have gone through the official documentations of the audio_service package ,In that example section the author has  created two fixed media items,In you are code u are fetching from cloud and you have made use of Dio,which i found little difficult to understand.What i am trying to achieve is that i need to fetch data from firebase and use that.

**Comment by rohansohonee** [comment]
The sample focuses on demonstrating audio playback. You can refer to Firebase docs for fetching data. Regarding Dio, I fetch the data in JSON, cache it & then decode. I also have some useful comments in the code so please have a look at those. You will also see a `musicCatalog.g.dart` file under the data folder. This is a generated file.
You can learn more at https://flutter.dev/docs/development/data-and-backend/json#serializing-json-using-code-generation-libraries
Closing this issue as it is unrelated. You can open a new issue, but it must pertain to audio playback.

**Comment by KM8Oz** [comment]
Thanks for that
